language: java
jdk: openjdk11
cache:
  directories:
    - .gradle
script:
  - "cd users-service-jpa"
  - "../gradlew test"
  - "cd ../database"
  - "../gradlew test"
  - "cd ../authorization-service-spring"
  - "../gradlew test"
  - "cd ../authorization-admin-service-spring"
  - "../gradlew test"
on:
  branch: master
