server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://172.18.0.3:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  oauth2:
    resource:
      id: http://localhost:9191/admin
logging:
  level:
    org:
      hibernate:
        type: trace