server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://192.168.111.20:3306/authDB?createDatabaseIfNotExist=true
    username: erudisch
    password: g9wfve6Jd4pVbNUs
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace